// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMY5zLJd0eBkoOKVqh6m5FaVgIx9kUEQA',
    appId: '1:583329359644:web:617f4cbf2c532b2f793cd9',
    messagingSenderId: '583329359644',
    projectId: 'spag-app-2b999',
    authDomain: 'spag-app-2b999.firebaseapp.com',
    storageBucket: 'spag-app-2b999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDae1JcpBR9h1BYz1jpxCqp0AaKzIC4i40',
    appId: '1:583329359644:android:516255c830bd72a9793cd9',
    messagingSenderId: '583329359644',
    projectId: 'spag-app-2b999',
    storageBucket: 'spag-app-2b999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEHJgKJitRFhfHzVv4wM5bq8IjPfwZN8',
    appId: '1:583329359644:ios:b7fffb0099d37a1c793cd9',
    messagingSenderId: '583329359644',
    projectId: 'spag-app-2b999',
    storageBucket: 'spag-app-2b999.appspot.com',
    iosClientId: '583329359644-r7d6mffm3c3eue9mi2m9mfl2cfkopp2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.spagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEHJgKJitRFhfHzVv4wM5bq8IjPfwZN8',
    appId: '1:583329359644:ios:b7fffb0099d37a1c793cd9',
    messagingSenderId: '583329359644',
    projectId: 'spag-app-2b999',
    storageBucket: 'spag-app-2b999.appspot.com',
    iosClientId: '583329359644-r7d6mffm3c3eue9mi2m9mfl2cfkopp2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.spagApp',
  );
}
